# Generated by Django 4.2.7 on 2023-12-22 18:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ageb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_geo', models.IntegerField()),
                ('cve_ent', models.IntegerField()),
                ('cve_mun', models.IntegerField()),
                ('cve_loc', models.IntegerField()),
                ('cve_ageb', models.IntegerField()),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
