# Generated by Django 4.2.7 on 2023-12-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_alter_ageb_cve_ageb_alter_ageb_cve_geo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ageb',
            name='cve_ageb',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='ageb',
            name='cve_geo',
            field=models.CharField(),
        ),
    ]
