# Generated by Django 4.2.7 on 2023-12-23 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_alter_ageb_cve_ageb_alter_ageb_cve_geo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgebVictimReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_category', models.CharField()),
                ('second_category', models.CharField()),
                ('ageb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.ageb')),
                ('victim_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.victimreport')),
            ],
        ),
    ]
