# Generated by Django 4.2.7 on 2023-12-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_agebvictimreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='ageb',
            name='bicicle_accidents_events_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ageb',
            name='bike_theft_events_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ageb',
            name='car_theft_events_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ageb',
            name='crash_accidents_events_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ageb',
            name='motorcicle_accidents_events_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ageb',
            name='motorcicle_theft_events_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ageb',
            name='pedestrian_accidents_events_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ageb',
            name='pedestrian_theft_events_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ageb',
            name='public_transport_assault_events_count',
            field=models.IntegerField(default=0),
        ),
    ]
