# Generated by Django 4.2.7 on 2023-12-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0006_ageb_bicicle_accidents_events_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ageb',
            name='car_accessories_theft_events_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ageb',
            name='car_internal_belongings_theft_events_count',
            field=models.IntegerField(default=0),
        ),
    ]
