# Generated by Django 4.2.7 on 2024-01-02 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0007_ageb_car_accessories_theft_events_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agebvictimreport',
            name='ageb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victim_reports', to='world.ageb'),
        ),
    ]
