# Generated by Django 4.2.7 on 2024-01-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0009_victimreport_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='ageb',
            name='bike_accidents_events_count',
            field=models.IntegerField(default=0),
        ),
    ]
