# Generated by Django 4.2.10 on 2024-03-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0011_conversation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='userID',
            new_name='deviceID',
        ),
        migrations.AddField(
            model_name='conversation',
            name='useCase',
            field=models.CharField(default=1, verbose_name=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversation',
            name='source',
            field=models.CharField(verbose_name=1),
        ),
    ]
