# Generated by Django 4.2.10 on 2024-03-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0012_rename_userid_conversation_deviceid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
